/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Brush: typeof import('./src/components/icons/Brush.vue')['default']
    CommonEditor: typeof import('./src/components/editor/CommonEditor.vue')['default']
    CommonPreview: typeof import('./src/components/preview/CommonPreview.vue')['default']
    ContentEditor: typeof import('./src/components/editor/ContentEditor.vue')['default']
    EditPart: typeof import('./src/components/EditPart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FieldManager: typeof import('./src/components/editor/FieldManager.vue')['default']
    ImageEditor: typeof import('./src/components/editor/ImageEditor.vue')['default']
    ImagePreview: typeof import('./src/components/preview/ImagePreview.vue')['default']
    InfoFilled: typeof import('./src/components/icons/InfoFilled.vue')['default']
    Layout: typeof import('./src/components/editor/Layout.vue')['default']
    MarketPart: typeof import('./src/components/MarketPart.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    ResumeCompPart: typeof import('./src/components/ResumeCompPart.vue')['default']
    ResumePreview: typeof import('./src/components/ResumePreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./src/components/Title.vue')['default']
    Upload: typeof import('./src/components/icons/Upload.vue')['default']
    ZoomIn: typeof import('./src/components/icons/ZoomIn.vue')['default']
    ZoomOut: typeof import('./src/components/icons/ZoomOut.vue')['default']
  }
}
