/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicInfoEditor: typeof import('./src/components/editor/BasicInfoEditor.vue')['default']
    BasicInfoPreview: typeof import('./src/components/preview/BasicInfoPreview.vue')['default']
    CommonEditor: typeof import('./src/components/editor/CommonEditor.vue')['default']
    CommonPreview: typeof import('./src/components/preview/CommonPreview.vue')['default']
    ContentEditer: typeof import('./src/components/editor/ContentEditer.vue')['default']
    ContentPreview: typeof import('./src/components/preview/ContentPreview.vue')['default']
    EditPart: typeof import('./src/components/EditPart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FieldManager: typeof import('./src/components/editor/FieldManager.vue')['default']
    Layout: typeof import('./src/components/editor/Layout.vue')['default']
    MarketPart: typeof import('./src/components/MarketPart.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    ResumeCompPart: typeof import('./src/components/ResumeCompPart.vue')['default']
    ResumePreview: typeof import('./src/components/ResumePreview.vue')['default']
    TitlePreview: typeof import('./src/components/preview/TitlePreview.vue')['default']
  }
}
